spring:
  sql:
    init:
      mode: never
  application:
    name: demo
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    jdbcUrl: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: "always"

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_URL}

app:
  resource: ${RESOURCE_FILE:.input/.}
  output: ${FILE_PATH}
  fileName: ${FILE_NAME}
